### ISSUE TITLE
Error decoding AAC frame. Code BEBBB1B7

### ISSUE THREAD

**Issue by rmcrackan** [Mbucari/AAXClean#13]
In [this ticket](https://github.com/rmcrackan/Libation/issues/800), `Error decoding AAC frame. Code BEBBB1B7` was thrown by AAXClean.

In Libation v11.2 I upgraded to .net8. Too many Mac users were getting weird errors so I deleted 11.2. This bug in question is neither Mac nor 11.2 so I'm considering it a legitimate bug.

**Comment by Mbucari** [comment]
Wow, I'm just not getting email notifications for any issues on my repos. I'll need to look into that...

Anyway, I checked this out with one of the titles from that ticket (thankfully it was a plus title), and it works flawlessly on my machine.  That's an ffmpeg error code and it means Invalid Data. The encoded AAC audio frame that was sent to the decoder was invalid. Since downgrading Libation fixed the issue, I'm chalking this up to the  same CLR error that was causing the other Libation weirdness.

On the topic of .NET 8 upgrade troubles, I wonder if they were caused by AAXClean still being .NET6.

**Comment by rmcrackan** [comment]
I had the same thought. Which is maddening. Why should that matter? I have the same issue with my Lucene fork -- every time I upgrade the .net version, I have to do it Lucene first. I use dozens of nuget pkg.s all the time and the others never have this problem. I don't know what they're doing right or I'm doing wrong.

Let me know if you ever decide to upgrade your .net version.

Thanks for taking time to check on this.

**Comment by Mbucari** [comment]
@rmcrackan I've added .NET 8 support to AAXClean and nuget packages are live.

**Comment by rmcrackan** [comment]
@Mbucari Finally getting through my emails. Crazy season.

Much thanks for the upgrade. I'll try a release today.

Hope you had a good Christmas :)

**Comment by rmcrackan** [comment]
@Mbucari I updated AAXClean.Codecs from 1.1.1 to 1.1.2 and I can no long see types like: AppleTags, AaxFile, Mp4Operation

**Comment by Mbucari** [comment]
@rmcrackan 
> I updated AAXClean.Codecs from 1.1.1 to 1.1.2 and I can no long see types like: AppleTags, AaxFile, Mp4Operation

Sorry about that and sorry it took so long to get to this. I just got back in town yesterday. I messed up the nuspec file when I added a second target framework. Fixed in 1.1.3.

**Comment by rmcrackan** [comment]
Thanks man. Building a new version now.
